"""Generate initial migration

Revision ID: d7293596f683
Revises: 
Create Date: 2025-07-17 01:40:35.712958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7293596f683'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_credit_card',
    sa.Column('card_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('member_key', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.Enum('visa', 'mastercard', 'amex', 'discover', name='dw_card_type'), nullable=True),
    sa.Column('credit_limit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('credit_limit_tier', sa.String(length=20), nullable=True),
    sa.Column('apr_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('apr_category', sa.String(length=20), nullable=True),
    sa.Column('card_status', sa.Enum('active', 'blocked', 'expired', 'closed', name='dw_card_status'), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('card_age_months', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date_scd', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('card_key')
    )
    op.create_table('dim_member',
    sa.Column('member_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('annual_income', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('income_bracket', sa.String(length=20), nullable=True),
    sa.Column('employment_status', sa.Enum('employed', 'self_employed', 'unemployed', 'retired', name='dw_employment_status'), nullable=True),
    sa.Column('member_since', sa.Date(), nullable=True),
    sa.Column('member_tenure_years', sa.Integer(), nullable=True),
    sa.Column('member_status', sa.Enum('active', 'inactive', 'suspended', name='dw_member_status'), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('member_key')
    )
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('annual_income', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('employment_status', sa.Enum('employed', 'self_employed', 'unemployed', 'retired', name='employment_status'), nullable=True),
    sa.Column('member_since', sa.Date(), nullable=True),
    sa.Column('member_status', sa.Enum('active', 'inactive', 'suspended', name='member_status'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('credit_cards',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('card_type', sa.Enum('visa', 'mastercard', 'amex', 'discover', name='card_type'), nullable=True),
    sa.Column('credit_limit', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('current_balance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('apr_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('minimum_payment', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('card_status', sa.Enum('active', 'blocked', 'expired', 'closed', name='card_status'), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('payment_history',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('minimum_due', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('on_time', 'late', 'missed', 'partial', name='payment_status'), nullable=False),
    sa.Column('days_late', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.card_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_history')
    op.drop_table('credit_cards')
    op.drop_table('members')
    op.drop_table('dim_member')
    op.drop_table('dim_credit_card')
    # ### end Alembic commands ###
