[project]
name = "api-backend"
version = "0.1.0"
description = "API Services for the UI."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic",
    "fastapi",
    "uvicorn",
    "psycopg2-binary", # PostgreSQL support
    "pymysql", # Add this for MySQL support
    "sqlalchemy",
    "uv",
    "cryptography",
    "python-dotenv",
    "pymongo",
    "dnspython",
    "auth>=0.5.3",
]





