"""Initial migration

Revision ID: f04dbc632d6f
Revises: 
Create Date: 2025-07-19 22:22:42.013192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04dbc632d6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_type', sa.Enum('credit_card', 'personal_loan', 'mortgage', 'savings_account', 'cd', 'investment'), nullable=True),
    sa.Column('product_category', sa.Enum('premium', 'standard', 'basic', 'secured'), nullable=True),
    sa.Column('interest_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('credit_limit_min', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('credit_limit_max', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('minimum_income_required', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('minimum_credit_score', sa.Integer(), nullable=True),
    sa.Column('maximum_debt_to_income', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('annual_fee', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('rewards_program', sa.String(length=100), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('annual_income', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('employment_status', sa.Enum('employed', 'self_employed', 'unemployed', 'retired'), nullable=True),
    sa.Column('member_since', sa.Date(), nullable=True),
    sa.Column('member_status', sa.Enum('active', 'inactive', 'suspended'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('credit_cards',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('card_type', sa.Enum('visa', 'mastercard', 'amex', 'discover'), nullable=True),
    sa.Column('credit_limit', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('current_balance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('apr_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('minimum_payment', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('card_status', sa.Enum('active', 'blocked', 'expired', 'closed'), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('financial_health_metrics',
    sa.Column('metric_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('debt_to_income_ratio', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('credit_utilization_ratio', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('payment_reliability_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('savings_balance', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('checking_balance', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_debt', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('number_of_accounts', sa.Integer(), nullable=True),
    sa.Column('recent_inquiries', sa.Integer(), nullable=True),
    sa.Column('delinquent_accounts', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('risk_category', sa.Enum('low', 'medium', 'high'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('payment_history',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('minimum_due', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('on_time', 'late', 'missed', 'partial'), nullable=False),
    sa.Column('days_late', sa.Integer(), nullable=True),
    sa.Column('late_fee', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('statement_balance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', sa.Enum('auto_pay', 'online', 'phone', 'mail', 'branch'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.card_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_history')
    op.drop_table('financial_health_metrics')
    op.drop_table('credit_cards')
    op.drop_table('members')
    op.drop_table('financial_products')
    # ### end Alembic commands ###
