"""Initial migration

Revision ID: 22efd51ec78f
Revises: 
Create Date: 2025-07-19 20:36:52.372973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22efd51ec78f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_date',
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('date_value', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_name', sa.String(length=10), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('day_of_year', sa.Integer(), nullable=True),
    sa.Column('week_of_year', sa.Integer(), nullable=True),
    sa.Column('month_number', sa.Integer(), nullable=True),
    sa.Column('month_name', sa.String(length=10), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('fiscal_month', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date_key')
    )
    op.create_table('dim_financial_product',
    sa.Column('product_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.Enum('credit_card', 'personal_loan', 'mortgage', 'savings_account', 'cd', 'investment', name='product_type'), nullable=True),
    sa.Column('product_category', sa.Enum('premium', 'standard', 'basic', 'secured', name='product_category'), nullable=True),
    sa.Column('interest_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('interest_rate_tier', sa.String(length=20), nullable=True),
    sa.Column('credit_limit_min', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('credit_limit_max', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('minimum_income_required', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('minimum_credit_score', sa.Integer(), nullable=True),
    sa.Column('maximum_debt_to_income', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('annual_fee', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('fee_category', sa.String(length=20), nullable=True),
    sa.Column('rewards_program', sa.String(length=100), nullable=True),
    sa.Column('has_rewards', sa.Boolean(), nullable=True),
    sa.Column('eligibility_tier', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('product_key')
    )
    op.create_table('dim_member',
    sa.Column('member_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('annual_income', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('income_bracket', sa.String(length=20), nullable=True),
    sa.Column('employment_status', sa.Enum('employed', 'self_employed', 'unemployed', 'retired', name='employment_status'), nullable=True),
    sa.Column('member_since', sa.Date(), nullable=True),
    sa.Column('member_tenure_years', sa.Integer(), nullable=True),
    sa.Column('member_status', sa.Enum('active', 'inactive', 'suspended', name='member_status'), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('member_key')
    )
    op.create_table('dim_payment_method',
    sa.Column('payment_method_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_method', sa.Enum('auto_pay', 'online', 'phone', 'mail', 'branch', name='payment_method'), nullable=True),
    sa.Column('payment_channel', sa.String(length=20), nullable=True),
    sa.Column('convenience_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('payment_method_key')
    )
    op.create_table('dim_credit_card',
    sa.Column('card_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('member_key', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.Enum('visa', 'mastercard', 'amex', 'discover', name='card_type'), nullable=True),
    sa.Column('credit_limit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('credit_limit_tier', sa.String(length=20), nullable=True),
    sa.Column('apr_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('apr_category', sa.String(length=20), nullable=True),
    sa.Column('card_status', sa.Enum('active', 'blocked', 'expired', 'closed', name='card_status'), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('card_age_months', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date_scd', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['member_key'], ['dim_member.member_key'], ),
    sa.PrimaryKeyConstraint('card_key')
    )
    op.create_table('fact_financial_health',
    sa.Column('health_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_key', sa.Integer(), nullable=False),
    sa.Column('assessment_date_key', sa.Integer(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('debt_to_income_ratio', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('credit_utilization_ratio', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('payment_reliability_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('savings_balance', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('checking_balance', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_debt', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('number_of_accounts', sa.Integer(), nullable=True),
    sa.Column('recent_inquiries', sa.Integer(), nullable=True),
    sa.Column('delinquent_accounts', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('total_liquid_assets', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('debt_to_assets_ratio', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('net_worth', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('risk_category', sa.String(length=10), nullable=True),
    sa.Column('credit_score_tier', sa.String(length=12), nullable=True),
    sa.Column('utilization_tier', sa.String(length=12), nullable=True),
    sa.Column('created_datetime', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_date_key'], ['dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['member_key'], ['dim_member.member_key'], ),
    sa.PrimaryKeyConstraint('health_key')
    )
    op.create_table('fact_product_recommendation',
    sa.Column('recommendation_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_key', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.Integer(), nullable=False),
    sa.Column('recommendation_date_key', sa.Integer(), nullable=False),
    sa.Column('expires_date_key', sa.Integer(), nullable=True),
    sa.Column('recommendation_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('member_health_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('credit_utilization_at_time', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('payment_reliability_at_time', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('recommendation_tier', sa.String(length=20), nullable=True),
    sa.Column('days_to_expiry', sa.Integer(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('is_high_confidence', sa.Boolean(), nullable=True),
    sa.Column('recommendation_status', sa.String(length=10), nullable=True),
    sa.Column('created_datetime', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_datetime', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['expires_date_key'], ['dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['member_key'], ['dim_member.member_key'], ),
    sa.ForeignKeyConstraint(['product_key'], ['dim_financial_product.product_key'], ),
    sa.ForeignKeyConstraint(['recommendation_date_key'], ['dim_date.date_key'], ),
    sa.PrimaryKeyConstraint('recommendation_key')
    )
    op.create_table('fact_credit_card_balance',
    sa.Column('balance_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_key', sa.Integer(), nullable=False),
    sa.Column('card_key', sa.Integer(), nullable=False),
    sa.Column('snapshot_date_key', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('current_balance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('available_credit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('minimum_payment', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('utilization_ratio', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('utilization_tier', sa.String(length=12), nullable=True),
    sa.Column('balance_trend', sa.String(length=20), nullable=True),
    sa.Column('is_over_limit', sa.Boolean(), nullable=True),
    sa.Column('is_high_utilization', sa.Boolean(), nullable=True),
    sa.Column('is_maxed_out', sa.Boolean(), nullable=True),
    sa.Column('created_datetime', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['card_key'], ['dim_credit_card.card_key'], ),
    sa.ForeignKeyConstraint(['member_key'], ['dim_member.member_key'], ),
    sa.ForeignKeyConstraint(['snapshot_date_key'], ['dim_date.date_key'], ),
    sa.PrimaryKeyConstraint('balance_key')
    )
    op.create_table('fact_payment',
    sa.Column('payment_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_key', sa.Integer(), nullable=False),
    sa.Column('card_key', sa.Integer(), nullable=False),
    sa.Column('payment_date_key', sa.Integer(), nullable=False),
    sa.Column('payment_method_key', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('minimum_due', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('statement_balance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('late_fee', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('days_late', sa.Integer(), nullable=True),
    sa.Column('payment_ratio', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('excess_payment', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_on_time', sa.Boolean(), nullable=True),
    sa.Column('is_full_payment', sa.Boolean(), nullable=True),
    sa.Column('is_minimum_payment', sa.Boolean(), nullable=True),
    sa.Column('is_over_payment', sa.Boolean(), nullable=True),
    sa.Column('payment_status', sa.String(length=10), nullable=False),
    sa.Column('created_datetime', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['card_key'], ['dim_credit_card.card_key'], ),
    sa.ForeignKeyConstraint(['member_key'], ['dim_member.member_key'], ),
    sa.ForeignKeyConstraint(['payment_date_key'], ['dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['payment_method_key'], ['dim_payment_method.payment_method_key'], ),
    sa.PrimaryKeyConstraint('payment_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_payment')
    op.drop_table('fact_credit_card_balance')
    op.drop_table('fact_product_recommendation')
    op.drop_table('fact_financial_health')
    op.drop_table('dim_credit_card')
    op.drop_table('dim_payment_method')
    op.drop_table('dim_member')
    op.drop_table('dim_financial_product')
    op.drop_table('dim_date')
    # ### end Alembic commands ###
